name: Make YouTube Short

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  build-short:
    runs-on: ubuntu-latest

    steps:
      - name: Get repo files
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install FFmpeg and ImageMagick
        run: sudo apt-get update && sudo apt-get install -y ffmpeg imagemagick

      - name: Install Python packages
        run: pip install moviepy==1.0.3 pillow numpy

      - name: Make video
        run: python make_short.py

      - name: Save video
        uses: actions/upload-artifact@v4
        with:
          name: generated-short
          path: output/*.mp4
